### ISSUE TITLE
ship with static libraries for an easier adoption

### ISSUE THREAD

**Issue by mark-kubacki** [chrisfelesoid/go-flif#1]
It will be easier to work with, and I guess adoption rate and visibility will get a bump up, if you shipped with static libraries (and the odd header file) for *flif*. For example, like it's done here for *zstd* (the `*.a` files for some popular architectures):  
https://github.com/valyala/gozstd

Hey, thanks for your package for Go, and thanks for looking into this!

**Comment by chrisfelesoid** [comment]
@wmark You are right!
I try it.

**Comment by chrisfelesoid** [comment]
I decided not to ship it. but I tried creating FLIF static library using Makefile instead of ship it.
